name: SnakeAnimation
on:
  schedule:
    - cron: "0 */6 * * *" 
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: eduardstal
          svg_out_path: dist/github-snake.svg
      - name: push github-snake.svg
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
